<a href="https://colab.research.google.com/github/Spandana2704/ML/blob/main/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data= {2014:[100.5,150.8,200.9,30000,40000],2015:[12000,18000,22000,30000,45000],2016:[20000,50000,70000,100000,125000],2017:[50000,60000,70000,80000,90000]}
names=['Madhu','Kusum','Kinshuk','Ankit','Shruti']
sales= pd.DataFrame(data,index=names)

In [ ]:
sales

2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000

In [ ]:
sales.index

Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')

In [ ]:
sales.columns

Index([2014, 2015, 2016, 2017], dtype='int64')

In [ ]:
sales.dtypes

2014    float64
2015      int64
2016      int64
2017      int64
dtype: object

In [ ]:
print("Dimensions:", sales.ndim)
print("Shape:", sales.shape)
print("Size:", sales.size)
print("Values:")
print(sales.values)

Dimensions: 2
Shape: (5, 4)
Size: 20
Values:
[[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]


In [ ]:
sales.tail(2)

2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000

In [ ]:
sales.iloc[:, :2]

2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000

In [ ]:
data = {2018: [160000, 110000, 500000, 340000, 900000]}
names = ["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"]
Sales2 = pd.DataFrame(data,index=names)
print(Sales2)

           2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000


In [ ]:
if Sales2.empty:
    print("Sales2 is empty")
else:
    print("Sales2 contains data")

Sales2 contains data


In [ ]:
Sales2.empty

False

In [ ]:
sales[2018] = Sales2[2018]

In [ ]:
sales

2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000

In [ ]:
sales = sales.T

In [ ]:
sales

Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0

In [ ]:
print(sales.loc[2017])

Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64


In [ ]:
print(sales.loc[[2017, 2018], ["Madhu", "Ankit"]])

         Madhu     Ankit
2017   50000.0   80000.0
2018  160000.0  340000.0


In [ ]:
print(sales.loc[2016, "Shruti"])

125000.0


In [ ]:
sales["Sumeet"] = [196.2, 37800, 52000, 78438, 38852]

In [ ]:
sales

Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2014     100.5     150.8     200.9   30000.0   40000.0    196.2
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0

In [ ]:
sales.drop(index=2014, inplace=True)

In [ ]:
sales

Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0

In [ ]:
sales.drop(columns="Kinshuk", inplace=True)

In [ ]:
sales

Madhu     Kusum     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0

In [ ]:
sales.rename(columns={"Ankit": "Vivaan", "Madhu": "Shailesh"}, inplace=True)

In [ ]:
sales

Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0

In [ ]:
sales.at[2018, "Shailesh"] = 100000

In [ ]:
sales

Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0

In [ ]:
sales.to_csv("SalesFigures.csv", index=False, header=False)

In [ ]:
SalesRetrieved = pd.read_csv("SalesFigures.csv", header=None)
SalesRetrieved.index = sales.index
SalesRetrieved.columns = sales.columns
print(SalesRetrieved)

      Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
import pandas as pd
data = {"Item": ["TV", "TV", "TV", "AC"],"Company": ["LG", "VIDEOCON", "LG", "SONY"],"Rupees": [12000, 10000, 15000, 14000],"USD": [700, 650, 800, 750]}
df = pd.DataFrame(data)
print(df)

  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750


In [ ]:
new_data = pd.DataFrame([
    {"Item": "TV", "Company": "SONY", "Rupees": 13000, "USD": 720},
    {"Item": "AC", "Company": "LG", "Rupees": 16000, "USD": 850}
])
df = pd.concat([df, new_data], ignore_index=True)
print(df)

  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
4   TV      SONY   13000  720
5   AC        LG   16000  850


In [ ]:
lg_tv_max = df[(df['Item'] == 'TV') & (df['Company'] == 'LG')]['Rupees'].max()
print("Maximum price of LG TV:", lg_tv_max)

Maximum price of LG TV: 15000


In [ ]:
total_rupees = df['Rupees'].sum()
print("Total sum of all products in Rupees:", total_rupees)

Total sum of all products in Rupees: 80000


In [ ]:
sony_median_usd = df[df['Company'] == 'SONY']['USD'].median()
print("Median USD for SONY products:", sony_median_usd)

Median USD for SONY products: 735.0


In [ ]:
sorted_df = df.sort_values(by='Rupees')
print(sorted_df)

  Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
4   TV      SONY   13000  720
3   AC      SONY   14000  750
2   TV        LG   15000  800
5   AC        LG   16000  850


In [ ]:
sorted_df = df.sort_values(by='Rupees')
print(sorted_df)

  Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
4   TV      SONY   13000  720
3   AC      SONY   14000  750
2   TV        LG   15000  800
5   AC        LG   16000  850


In [ ]:
import numpy as np
data = {"Name": ["Aparna", "Pankaj", "Ram", "Ramesh", "Naveen", "Krrishnav", "Bhawna"],"Degree": ["MBA", "BCA", "M.Tech", "MBA", np.nan, "BCA", "MBA"],"Score": [90.0, np.nan, 80.0, 98.0, 97.0, 78.0, 89.0]}
df2 = pd.DataFrame(data)
print(df2)

        Name  Degree  Score
0     Aparna     MBA   90.0
1     Pankaj     BCA    NaN
2        Ram  M.Tech   80.0
3     Ramesh     MBA   98.0
4     Naveen     NaN   97.0
5  Krrishnav     BCA   78.0
6     Bhawna     MBA   89.0


In [ ]:
print(df2.groupby("Degree")["Score"].max())

Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
Name: Score, dtype: float64


In [ ]:
df_filled = df2["Score"].fillna(76)
print(df_filled)

0    90.0
1    76.0
2    80.0
3    98.0
4    97.0
5    78.0
6    89.0
Name: Score, dtype: float64


In [ ]:
df2.set_index("Name", inplace=True)
print(df2)

           Degree  Score
Name                    
Aparna        MBA   90.0
Pankaj        BCA    NaN
Ram        M.Tech   80.0
Ramesh        MBA   98.0
Naveen        NaN   97.0
Krrishnav     BCA   78.0
Bhawna        MBA   89.0


In [ ]:
df2.reset_index(inplace=True)
avg_scores = df2.groupby(["Name", "Degree"])["Score"].mean()
print(avg_scores)


Name       Degree
Aparna     MBA       90.0
Bhawna     MBA       89.0
Krrishnav  BCA       78.0
Pankaj     BCA        NaN
Ram        M.Tech    80.0
Ramesh     MBA       98.0
Name: Score, dtype: float64


In [ ]:
mba_count = df2[df2["Degree"] == "MBA"].shape[0]
print("Number of MBA students:", mba_count)

Number of MBA students: 3


In [ ]:
bca_mode = df2[df2["Degree"] == "BCA"]["Score"].mode()
print("Mode of BCA scores:", bca_mode.values)

Mode of BCA scores: [78.]


In [2]:
import pandas as pd
import numpy as np

In [7]:
column_names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
                'acceleration', 'model_year', 'origin', 'car_name']
autodf = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data', names=column_names, delim_whitespace=True, na_values='?')

/tmp/ipython-input-7-2969503220.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  autodf = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data', names=column_names, delim_whitespace=True, na_values='?')


In [8]:
autodf

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0  3504.0          12.0   
1    15.0          8         350.0       165.0  3693.0          11.5   
2    18.0          8         318.0       150.0  3436.0          11.0   
3    16.0          8         304.0       150.0  3433.0          12.0   
4    17.0          8         302.0       140.0  3449.0          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0  2790.0          15.6   
394  44.0          4          97.0        52.0  2130.0          24.6   
395  32.0          4         135.0        84.0  2295.0          11.6   
396  28.0          4         120.0        79.0  2625.0          18.6   
397  31.0          4         119.0        82.0  2720.0          19.4   

     model_year  origin                   car_name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [9]:
print(autodf.describe())

              mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year      origin  
count    398.000000  398.000000  398.000000  
mean      15.568090   76.010050    1.572864  
std        2.757689    3.697627    0.802055  
min        8.000000   70.000000    1.000000  
25%       13.825000   73.000000    1.000000  
50%       15.500000   76.000000    1.000000  
75%       17.175000   79.0000

In [10]:
print(autodf.head(10))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0  3504.0          12.0   
1  15.0          8         350.0       165.0  3693.0          11.5   
2  18.0          8         318.0       150.0  3436.0          11.0   
3  16.0          8         304.0       150.0  3433.0          12.0   
4  17.0          8         302.0       140.0  3449.0          10.5   
5  15.0          8         429.0       198.0  4341.0          10.0   
6  14.0          8         454.0       220.0  4354.0           9.0   
7  14.0          8         440.0       215.0  4312.0           8.5   
8  14.0          8         455.0       225.0  4425.0          10.0   
9  15.0          8         390.0       190.0  3850.0           8.5   

   model_year  origin                   car_name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1    

In [11]:
print(autodf.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64


In [12]:
autodf_ffill = autodf.fillna(method='ffill')

/tmp/ipython-input-12-3956724607.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  autodf_ffill = autodf.fillna(method='ffill')


In [13]:
autodf_dropna = autodf.dropna()

In [14]:
max_mpg_row = autodf.loc[autodf['mpg'].idxmax()]
print(max_mpg_row)

mpg                  46.6
cylinders               4
displacement         86.0
horsepower           65.0
weight             2110.0
acceleration         17.9
model_year             80
origin                  3
car_name        mazda glc
Name: 322, dtype: object


In [15]:
avg_displacement = autodf.groupby('cylinders')['displacement'].mean()
print(avg_displacement)

cylinders
3     72.500000
4    109.796569
5    145.000000
6    218.142857
8    345.009709
Name: displacement, dtype: float64


In [16]:
avg_cylinders = autodf['cylinders'].mean()
print("Average number of cylinders:", avg_cylinders)

Average number of cylinders: 5.454773869346734


In [17]:
average_weight = autodf['weight'].mean()
count_heavy_cars = (autodf['weight'] > average_weight).sum()
print("Number of cars with weight greater than average:", count_heavy_cars)

Number of cars with weight greater than average: 171
