<a href="https://colab.research.google.com/github/Spandana2704/ML/blob/main/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data= {2014:[100.5,150.8,200.9,30000,40000],2015:[12000,18000,22000,30000,45000],2016:[20000,50000,70000,100000,125000],2017:[50000,60000,70000,80000,90000]}
names=['Madhu','Kusum','Kinshuk','Ankit','Shruti']
sales= pd.DataFrame(data,index=names)

In [ ]:
sales

2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000

In [ ]:
sales.index

Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')

In [ ]:
sales.columns

Index([2014, 2015, 2016, 2017], dtype='int64')

In [ ]:
sales.dtypes

2014    float64
2015      int64
2016      int64
2017      int64
dtype: object

In [ ]:
print("Dimensions:", sales.ndim)
print("Shape:", sales.shape)
print("Size:", sales.size)
print("Values:")
print(sales.values)

Dimensions: 2
Shape: (5, 4)
Size: 20
Values:
[[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]


In [ ]:
sales.tail(2)

2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000

In [ ]:
sales.iloc[:, :2]

2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000

In [ ]:
data = {2018: [160000, 110000, 500000, 340000, 900000]}
names = ["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"]
Sales2 = pd.DataFrame(data,index=names)
print(Sales2)

           2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000


In [ ]:
if Sales2.empty:
    print("Sales2 is empty")
else:
    print("Sales2 contains data")

Sales2 contains data


In [ ]:
Sales2.empty

False

In [ ]:
sales[2018] = Sales2[2018]

In [ ]:
sales

2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000

In [ ]:
sales = sales.T

In [ ]:
sales

Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0

In [ ]:
print(sales.loc[2017])

Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64


In [ ]:
print(sales.loc[[2017, 2018], ["Madhu", "Ankit"]])

         Madhu     Ankit
2017   50000.0   80000.0
2018  160000.0  340000.0


In [ ]:
print(sales.loc[2016, "Shruti"])

125000.0


In [ ]:
sales["Sumeet"] = [196.2, 37800, 52000, 78438, 38852]

In [ ]:
sales

Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2014     100.5     150.8     200.9   30000.0   40000.0    196.2
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0

In [ ]:
sales.drop(index=2014, inplace=True)

In [ ]:
sales

Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0

In [ ]:
sales.drop(columns="Kinshuk", inplace=True)

In [ ]:
sales

Madhu     Kusum     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0

In [ ]:
sales.rename(columns={"Ankit": "Vivaan", "Madhu": "Shailesh"}, inplace=True)

In [ ]:
sales

Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0

In [ ]:
sales.at[2018, "Shailesh"] = 100000

In [ ]:
sales

Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0

In [ ]:
sales.to_csv("SalesFigures.csv", index=False, header=False)

In [ ]:
SalesRetrieved = pd.read_csv("SalesFigures.csv", header=None)
SalesRetrieved.index = sales.index
SalesRetrieved.columns = sales.columns
print(SalesRetrieved)

      Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
import pandas as pd
data = {"Item": ["TV", "TV", "TV", "AC"],"Company": ["LG", "VIDEOCON", "LG", "SONY"],"Rupees": [12000, 10000, 15000, 14000],"USD": [700, 650, 800, 750]}
df = pd.DataFrame(data)
print(df)

  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750


In [ ]:
new_data = pd.DataFrame([
    {"Item": "TV", "Company": "SONY", "Rupees": 13000, "USD": 720},
    {"Item": "AC", "Company": "LG", "Rupees": 16000, "USD": 850}
])
df = pd.concat([df, new_data], ignore_index=True)
print(df)

  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
4   TV      SONY   13000  720
5   AC        LG   16000  850


In [ ]:
lg_tv_max = df[(df['Item'] == 'TV') & (df['Company'] == 'LG')]['Rupees'].max()
print("Maximum price of LG TV:", lg_tv_max)

Maximum price of LG TV: 15000


In [ ]:
total_rupees = df['Rupees'].sum()
print("Total sum of all products in Rupees:", total_rupees)

Total sum of all products in Rupees: 80000


In [ ]:
sony_median_usd = df[df['Company'] == 'SONY']['USD'].median()
print("Median USD for SONY products:", sony_median_usd)

Median USD for SONY products: 735.0


In [ ]:
sorted_df = df.sort_values(by='Rupees')
print(sorted_df)

  Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
4   TV      SONY   13000  720
3   AC      SONY   14000  750
2   TV        LG   15000  800
5   AC        LG   16000  850


In [ ]:
sorted_df = df.sort_values(by='Rupees')
print(sorted_df)

  Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
4   TV      SONY   13000  720
3   AC      SONY   14000  750
2   TV        LG   15000  800
5   AC        LG   16000  850


In [ ]:
import numpy as np
data = {"Name": ["Aparna", "Pankaj", "Ram", "Ramesh", "Naveen", "Krrishnav", "Bhawna"],"Degree": ["MBA", "BCA", "M.Tech", "MBA", np.nan, "BCA", "MBA"],"Score": [90.0, np.nan, 80.0, 98.0, 97.0, 78.0, 89.0]}
df2 = pd.DataFrame(data)
print(df2)

        Name  Degree  Score
0     Aparna     MBA   90.0
1     Pankaj     BCA    NaN
2        Ram  M.Tech   80.0
3     Ramesh     MBA   98.0
4     Naveen     NaN   97.0
5  Krrishnav     BCA   78.0
6     Bhawna     MBA   89.0


In [ ]:
print(df2.groupby("Degree")["Score"].max())

Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
Name: Score, dtype: float64


In [ ]:
df_filled = df2["Score"].fillna(76)
print(df_filled)

0    90.0
1    76.0
2    80.0
3    98.0
4    97.0
5    78.0
6    89.0
Name: Score, dtype: float64


In [ ]:
df2.set_index("Name", inplace=True)
print(df2)

           Degree  Score
Name                    
Aparna        MBA   90.0
Pankaj        BCA    NaN
Ram        M.Tech   80.0
Ramesh        MBA   98.0
Naveen        NaN   97.0
Krrishnav     BCA   78.0
Bhawna        MBA   89.0


In [ ]:
df2.reset_index(inplace=True)
avg_scores = df2.groupby(["Name", "Degree"])["Score"].mean()
print(avg_scores)


Name       Degree
Aparna     MBA       90.0
Bhawna     MBA       89.0
Krrishnav  BCA       78.0
Pankaj     BCA        NaN
Ram        M.Tech    80.0
Ramesh     MBA       98.0
Name: Score, dtype: float64


In [ ]:
mba_count = df2[df2["Degree"] == "MBA"].shape[0]
print("Number of MBA students:", mba_count)

Number of MBA students: 3


In [ ]:
bca_mode = df2[df2["Degree"] == "BCA"]["Score"].mode()
print("Mode of BCA scores:", bca_mode.values)

Mode of BCA scores: [78.]
